[package]
name = "crab-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.2", features = ["gfx"] }
rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
